app_name="beepkg"
app_secret="123456" #用于对敏感数据进行加密

[web]
enabled=false
name=""
is_recovery=true
is_slash=true
secret_key="123456"
enable_docs=false

[web.gzip]
enable=false
level=-1

[web.auth]
enabled=false
email=true

[web.realtime]
enabled=true
broker="nats"
conn="nats://localhost:4222"

[web.pubsub]
enabled=false
broker="nats"
conn="nats://localhost:4222"

[web.fileStore]
enabled=false
storeType="local"
conn="./"
[[web.fileStore.rules]]
prefix="/"
create="allow"
read=""
delete=""

[web.view]
enabled=false
view_path="views"
html_pattern=""
html_files=[]
delims=["{{", "}}"]

[web.functions]
enabled=true
broker="nats"
conn="nats://localhost:4222"
rule="allow"

[web.static]
enabled=false
#静态文件目录设置，默认是static
dir=["static"]
#允许哪些后缀名的静态文件进行gzip压缩，默认支持.css和.js
ExtensionsToGzip=[".css",".js"]

[web.logger]
enabled=false
UTC=false
skip_path=[""]
skip_path_regex=""

[web.forcessl]
enabled=false
trustXFPHeader = false
enable301Redirects = false
message=""

[web.xsrf]
enabled=false
#XSRF的key信息，默认值是beegoxsrf
key="123456"
#XSRF过期时间，默认值是0，不过期。
expire=0

[web.upload]
enabled=false
file_max_size=12
file_ext=[""]
prefix="file_"
# oss, location
storage_type="oss"
oss_name=""
save_location=""

[web.server]
graceful=false
addr=":8080"
# app.domain
unix_socket=""

[web.jwt]
enabled=false
realm="Jwt"
signing_algorithm="RS256"
pub_key_file="jwt.key.public"
priv_key_file="jwt.key.private"
key="secret key"
timeout="24h"
max_refresh="216h"
identity_key="id"
token_lookup="header: Authorization, query: token, cookie: jwt"
token_head_name="Bearer"

[web.cors]
enabled=false
allow_all_origins=false
allow_origins=[""]
allow_regex_origins=[""]
allow_methods=["POST, GET, PUT, DELETE, OPTIONS"]
allow_headers=["Origin", "Content-Length", "Content-Type", "Token", "Authorization", "SessionKey", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers"]
expose_headers=[""]
allow_credentials=true
allow_wildcard=false
allow_web_sockets=false
allow_files=false
max_age=1

[web.cookie]
enabled=false
flash_name="BEEGO_FLASH"
flash_separator="BEEGOFLASH"
auto_set_cookie=true
expire=3600

[web.db]
driver="rds"
name="rds"

[web.session]
enabled=false
name="test"

driver="redis"
driver_name="test"

expire=3600

key_pairs=[""]

key_prefix="session_"
path="/"
max_age=1
secure=false
http_only=false
same_site=1
domain=""

[web.admin]
#是否开启进程内监控模块，默认false关闭。
enabled=false
#监控程序监听的地址，默认值是localhost。
addr="localhost"
port=9099
user= ""
pass= ""
role= ""
secret= ""

[http]
enabled=false
charset="UTF-8"
# https://github.com/go-resty/resty
[http.client]

[mongodb]
enabled=false
default="abc"
[[mongodb.cfg]]
name=""
database=""
url="mongodb+srv://<username>:<password>@<cluster-address>/test?w=majority"
host=""
port=27017
db=""
username=""
password=""
repositories_enabled=false
auth_mechanism=""
auth_mechanism_properties={}
auth_source=""
password_set=false
app_name=""
connect_timeout=1
compressors=[""]
heartbeat_interval=1
hosts=[""]
local_threshold=1
max_conn_idle_time=1
max_pool_size=1
replica_set=1
retry_writes=false
retry_reads=false
server_selection_timeout=1
direct=false
socket_timeout=1
zlib_level=1
authenticate_to_anything=false


[rds]
enabled=false
default="abc"
# database table prefix
prefix=""

[[rds.cfg]]
name="abc"

url="mysql://admin:123456@(127.0.0.1:3306)/mydb"
driver="mysql"
user="root"
pass="rootpass"
db="mydb"

initialize=true
schema=""
data=""
sql_script_encoding=""
platform=""
separator=""
username=""
password=""
max_active=100
max_idle=8
max_open=8
min_idle=8
max_lfetime=1
initial_size=10
validation_query=""
max_wait=""

[redis]
enabled=false
default=""
[[redis.cfg]]
name="abc"
url=""
user="root"
db=1
network=""
addr=""
password=""
max_retries=1
max_retry=1
dial_timeout=1
read_timeout=1
write_timeout=1
max_conn_age=1

pool_size=1
pool_timeout=1

idle_timeout=1
idle_check_frequency=1

[search]
enabled=false
[search.es]
enabled=false
default=""
[[search.es.cfg]]
name=""

[mq]
enabled=false
[mq.rabbitMQ]
enabled=false
default=""
default_exchange=""
publish_retry_time=1
default_priority=""
default_x_max_priority=10
default_x_queue_mode="lazy"
default_routing_key=""

[[mq.rabbitMQ.cfg]]
name="abc"
url="amqp://guest:guest@127.0.0.1:5673"
username="root"
password="rootpass"
port=5673
host="127.0.0.1"
virtual_host=""
dynamic=""

[[mq.rabbitMQ.cfg.channel]]
routing_key=""
exchange_name=""

# direct,fanout,topic
exchange_type="topic"
queue_name="test"
consumer=""
x-max-priority=10
x-queue-mode="lazy"
durable=true
auto_delete=false
exclusive=false
no_wait=false
no_local=false
auto_ack=false
prefetch_count=10
prefetch_size=10
global=false

[storage]
enabled=false
[storage.oss]
enabled=false
default=""
endpoint=""
out_endpoint=""
access_key_id=""
access_key_secret=""
retry_times=1
user_agent=""
is_debug=false
timeout=0
security_token=""
http_timeout=1
http_maxConns=1
is_use_proxy=false
proxy_host=""
is_auth_proxy=false
proxy_user=""
proxy_password=""
is_enable_md5=false
[[storage.oss.cfg]]
name=""
url="oss://id:key@oss-cn-shanghai-internal.aliyuncs.com"
save_oss_path=""
bucket=""
oss_path=""
endpoint=""
out_endpoint=""
access_key_id=""
access_key_secret=""
retry_times=1
user_agent=""
is_debug=false
timeout=0
security_token=""
http_timeout=1
http_maxConns=1
is_use_proxy=false
proxy_host=""
is_auth_proxy=false
proxy_user=""
proxy_password=""
is_enable_md5=false

[storage.file]
enabled=false
default=""
[[storage.file.cfg]]
name=""

[cache]
enabled=false
default=""
[[cache.cfg]]
driver="redis"
redis_name=""

[send_cloud]
enabled=false
default=""
[[send_cloud.cfg]]
api_user=""
api_key=""
encoding="UTF-8"

[[send_cloud.cfg.email]]
api_user=""
api_key=""
encoding="UTF-8"
[send_cloud.email]
default=""
enabled=false
[[send_cloud.email.cfg]]
name=""
url=""
api_user=""
api_key=""
from=""
from_name=""
encoding="UTF-8"

[[send_cloud.cfg.sms]]
[send_cloud.sms]
[[send_cloud.sms.cfg]]
name=""
url=""
api_user=""
api_key=""
msg_type=""
template_id=""
from=""
from_name=""

# 邮件服务器配置，用于邮件通知
[email]
enabled=false
default=""
[[email.cfg]]
Addr="smtp.qq.com"
Port=25
Username="请配置成你自己的"
Password="请配置成你自己的"
SSL="true"
name=""
driver="send_cloud"
driver_name="send_cloud"

[sms]
enabled=false
default=""
[[sms.cfg]]
name=""
driver="send_cloud"
driver_name="send_cloud"

[social]
enabled=false
[social.facebook]
enabled=false
default=""
[[social.facebook.cfg]]
app_id=""
app_secret=""
[social.linkedin]
enabled=false
default=""
[[social.linkedin.cfg]]
app_id=""
app_secret=""
[social.twitter]
enabled=false
default=""
[[social.twitter.cfg]]
app_id=""
app_secret=""
# github登录配置
[social.Github]
enabled=false
default=""
[[social.Github.cfg]]
ClientID=""
ClientSecret=""
# qq登录配置
[social.QQConnect]
enabled=false
default=""
[[social.QQConnect.cfg]]
ClientID=""
ClientSecret=""

[services]
default=""
[[services.cfg]]
captcha=""

[log]
enabled=true
time_format ="2006-01-02 15:04:05"
log_level="error"
timestamp_field_name = "time"
level_field_name = "level"
message_field_name = "message"
error_field_name = "error"
caller_field_name = "caller"
error_stack_field_name= "stack"
output_type="console" # console|file
filename="file.log"
max_size = 50000000
# 是否旋转日志,当日志达到max_size将会执行
rotate = true

[pay]
enabled=false
[pay.aliPay]
enabled=false
default=""
[[pay.aliPay.cfg]]
name=""
public_key=""
private_key=""
app_id="123456"
gateway_url="https://openapi.alipay.com/gateway.do"
sign_type="RSA"

[memcached]
enabled=false
default=""
[[memcached.cfg]]
name=""
servers=[""]
timeout=0
max_idle_conns=-1

[grpc]
enabled=false
default=""
[[grpc.cfg]]
port=9000
name=""

[ext]
